[unix_http_server]
file=/var/packages/AutoBangumi/target/app/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
childlogdir=/var/packages/AutoBangumi/target/logs
logfile=/var/packages/AutoBangumi/target/logs/supervisord.log
pidfile=/var/packages/AutoBangumi/target/app/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/packages/AutoBangumi/target/app/supervisor.sock

[program:AutoBangumi]
; 启动位置
directory=/var/packages/AutoBangumi/target/app
; 启动命令
command=/var/packages/AutoBangumi/target/bin/python main.py
; 是否自动重启
autostart=true
autorestart=true
; 等待时间
startsecs=5
; 启动进程数
numprocs=1
; 重试次数
startretries=3
; 是否杀死子进程
killasgroup=true
stopasgroup=true
; 日志输出控制台
redirect_stderr=true
; 日志保存最大 10M
stdout_logfile_maxbytes=10MB
; 日志保存最大七天
stdout_logfile_backups=3
